markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: pygments
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: sgamerw.github.io
title: WuZheng's Blog
description: Cocos2d-x, reading...
author: Jacky Woo
email: wuzheng68#hotmail.com
github: sgamerw

config:
  js_dir:
  img_dir:
  css_dir:
